services:
    db:
        image: postgres:15-alpine
        restart: on-failure:10
        ports:
            - 5432:5432
        environment:
            - POSTGRES_USER=${DB_USERNAME?err}
            - POSTGRES_PASSWORD=${DB_PASSWORD?err}
            - POSTGRES_DB=${DB_NAME?err}
        volumes:
            - .db:/var/lib/postgresql/data

    cache:
        image: redis:6-alpine
        restart: on-failure:10
        command: /bin/sh -c "redis-server --requirepass ${REDIS_PASSWORD}"
        ports:
            - 6379:6379
        volumes:
            - .cache:/data

networks:
    default:
        name: synopsis
        external: false
