global:
    scrape_interval: 10s
    evaluation_interval: 10s

    external_labels:
        monitor: 'monopsis-monitor'

rule_files:
    # -"first.rules"

scrape_configs:
    - job_name: 'prometheus'
      static_configs:
          - targets:
                - localhost:9090

    - job_name: 'traefik'
      static_configs:
          - targets:
                - traefik:8080

    - job_name: 'grafana'
      static_configs:
          - targets:
                - grafana:3000

    - job_name: 'node_exporter'
      static_configs:
          - targets:
                - node_exporter:9100

    - job_name: 'loki'
      static_configs:
          - targets:
                - loki:3100
