name: CD

on:
    workflow_run:
        workflows:
            - 'CI'
        branches: [main]
        types:
            - completed
    workflow_dispatch:

jobs:
    deploy:
        runs-on: ubuntu-latest
        if: ${{ github.event.workflow_run.conclusion == 'success' }}
        steps:
            - name: SSH into VPS, and docker-compose up with rebuild
              uses: appleboy/ssh-action@master
              with:
                  host: ${{ secrets.VPS_IP }}
                  username: ${{ secrets.VPS_USER }}
                  password: ${{ secrets.VPS_PASSWORD }}
                  script_stop: true
                  script: |
                      cd bot/
                      git pull
                      docker compose up -d --build website
                  # TODO: dockerize bot

    warn:
        runs-on: ubuntu-latest
        if: ${{ github.event.workflow_run.conclusion == 'failure' }}
        steps:
            - run: echo 'Tests failed, did not attempt to deploy.'
