name: CD

on:
    push:
        branches: [main]
    workflow_dispatch:

jobs:
    cd:
        if: github.repository == 'synopsisgg/bot'
        runs-on: ubuntu-latest

        steps:
            - name: Wait for CI to finish
              uses: lewagon/wait-on-check-action@v1.3.1
              with:
                  ref: ${{ github.ref }}
                  check-name: 'ci'
                  repo-token: ${{ secrets.GITHUB_TOKEN }}
                  verbose: true
                  wait-interval: 8

            - name: SSH into VPS, and docker-compose up with rebuild
              uses: appleboy/ssh-action@master
              with:
                  host: ${{ secrets.VPS_IP }}
                  username: ${{ secrets.VPS_USER }}
                  password: ${{ secrets.VPS_PASSWORD }}
                  script_stop: true
                  script: |
                      cd bot/
                      git pull
                      docker compose up -d --build website
                  # TODO: dockerize bot
