name: Sync

on:
    schedule:
        # Runs every 12 hours
        - cron: '0 */12 * * *'
    workflow_dispatch:

jobs:
    sync:
        name: Sync
        runs-on: ubuntu-latest
        if: github.repository == 'synopsisgg/bot'

        steps:
            - name: SSH into the server and run rclone
              uses: appleboy/ssh-action@master
              with:
                  host: ${{ secrets.VPS_IP }}
                  username: ${{ secrets.VPS_USER }}
                  password: ${{ secrets.VPS_PASSWORD }}
                  script_stop: true
                  script: |
                      cd
                      rclone sync volumes /tmp/volumes-sync --progress
                      rclone sync /tmp/volumes-sync google:backups/${{github.repository}}/sync --progress
                      rm -rf /tmp/volumes-sync
